-- This script prints the full description of the table first_table.
-- Task: Print the full description of the table first_table.

SELECT TABLE_NAME, CREATE_TIME, TABLE_TYPE, ENGINE, TABLE_COLLATION, TABLE_ROWS, AVG_ROW_LENGTH, DATA_LENGTH, MAX_DATA_LENGTH, INDEX_LENGTH, DATA_FREE, AUTO_INCREMENT, CREATE_OPTIONS, TABLE_COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'first_table';
